.TH IMGPROCESSLIB 1 "06 August 2023" "1.0" "Image Processing Library for Web"
.SH NAME
imgprocess \- Simple Image Processing Library for Web
.SH SYNOPSIS
.B imgprocess
.I 
.SH DESCRIPTION
.B processlib
imgprocess is a command-line tool that provides basic image processing functionalities for preparing images
to be used in fast-rendered websites. The user can load an image, resize, crop, rotate, and save the processed
image in various formats. Are you tired of using bloat software just to do simple task an resize, crop or rotate
image, this program is for you!

is a simple command-line tool for image processing, primarily aimed at preparing images for web usage. It provides various options to resize, crop, and rotate images. The program supports popular image formats, including PNG, JPEG, BMP, and GIF.
.SH USAGE
.B processlib
is used interactively and will prompt the user for inputs.
.SH EXAMPLES
Resize an image to a custom size:
.nf
.BR $ imgprocess
Enter path to picture: /path/to/input/image.png
Choose option:
1 Resize image
2 Crop image
3 Rotate image
4 Quit without saving
Option number: 1
Resize option number: 11
Enter WIDTH [pixels]: 800
Enter HEIGHT [pixels]: 600
Enter new name [example.png]: /path/to/output/resized_image.png
Proceed with new dimensions? [Y,n] Y
New photo size is 1440000 B
Successfully changed dimensions! Image saved to /path/to/output/resized_image.png!
.SH AUTHORS
.B processlib
was developed by Vidoje Šević <vidoje.sevic.275.19@ict.edu.rs>.
.SH SEE ALSO
.BR stb_resize(3),
.BR stb_image(3),
.BR stb_image_write(3)
.SH BUGS
Report any bugs or issues to <vidoje.sevic.275.19@ict.edu.rs>.

